lib/games_lobby_web/router.ex
defmodule GamesLobbyWeb.Router do
  use GamesLobbyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GamesLobbyWeb.Plugs.PlayerAuthPlug, repo: GamesLobby.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GamesLobbyWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/game", GamesController, :index
    resources "/players", PlayerController
    resources "/sessions", PlayerSessionController, only: [:new, :create, :delete]
    get "/sessions/sign-out", PlayerSessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", GamesLobbyWeb do
  #   pipe_through :api
  # end
end

lib/games_lobby_web/views/layout_view.ex
defmodule GamesLobbyWeb.LayoutView do
  use GamesLobbyWeb, :view
end

lib/games_lobby_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GamesLobby!</title>

    <%= if assigns[:custom_css] do %>
      <style>
        #authBlock{
          float: right;
          padding: 15px;
        }
        /*body {
          background-image: url("images/hexaboard/tiles/dark_wood.png");
          background-repeat: repeat;
        } */
      </style>
    <% else %>
      <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <% end %> 
  </head>

  <body>
    
    <%= if assigns[:elm_app_path] do %>
      <script src="<%= static_path(@conn, assigns[:elm_app_path]) %>"></script> 
    <% else %>
      <span></span>
    <%end %>
    
    <div class="container">
      <%= if assigns[:elm_app_path] do %>
        <span></span>
      
      <% else %>

        <header class="header">
          <nav role="navigation" id="authBlock">
            <ul class="nav nav-pills pull-right">
             <%= if @current_player do %> 
               <p class="small">Signed in as <strong><%= @current_player.username %></strong></p>
               <%= link "Sign Out", to: player_session_path(@conn, :delete, @current_player), method: "delete", class: "btn btn-sm btn-danger" %>
             <% else %>  
               <%= link "Sign Up", to: player_path(@conn, :new), class: "btn btn-sm btn-success" %>
               <%= link "Sign In", to: player_session_path(@conn, :new), class: "btn btn-sm btn-primary" %>
            <% end %>
            </ul>
          </nav>
          <span class="logo"></span>
        </header>

      <%end %>
      
      <%= if assigns[:custom_css] && @current_player do %>
      
        <span></span>
      
      <% else %>

        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      
      <% end %> 

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

  </body>
</html>